name: CI

on:
  push:

defaults:
  run:
    shell: bash

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: extractions/setup-just@v1
      with:
        just-version: '1.5.0'
    ## Rust
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - uses: Swatinem/rust-cache@v2
    - run: cargo test
    ## Python
    - uses: actions/setup-python@v2
    - uses: syphar/restore-virtualenv@v1
      id: cache-virtualenv
      with:
        requirement_files: requirements.dev.txt
    - uses: syphar/restore-pip-download-cache@v1
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'
    - run: pip install -r requirements.dev.txt
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'
    - name: Print dependencies
      run: python3 --version && python3 -m pip freeze
    - run: . /home/runner/.virtualenvs/.venv/bin/activate && just test
    - run: . /home/runner/.virtualenvs/.venv/bin/activate && just lint